 USE atharva;

SELECT * FROM movies;

# Movies with rating > 8
SELECT * FROM movies
WHERE Rating > 8;


# Distinct Genres 
SELECT DISTINCT Genre 
FROM movies;


# Movie released in specific year
SELECT Title, Year
FROM movies 
WHERE Year = 2023;


# Count of movies Genre wise
SELECT Genre, COUNT(*) AS movie_count
FROM movies
GROUP BY Genre;


# Avg. rating Director wise
SELECT Director, AVG(Rating) AS avg_rating
FROM movies
GROUP BY Director;


# Top rated movie
SELECT * FROM movies
ORDER BY Rating 
DESC LIMIT 1;


# Movies with revenue above Average revenue
SELECT Title, Revenue
FROM movies
WHERE Revenue > ( SELECT AVG(Revenue) FROM movies );


# Movies with title cast and director
SELECT Title, Director, cast
FROM movies
WHERE Title = 'Soorarai Pottru'
GROUP BY Title;


# Highest grossing movie Genre wise
SELECT Genre, Title, Revenue
FROM (
      SELECT Genre, Title, Revenue,
			 ROW_NUMBER() OVER (PARTITION BY Genre ORDER BY Revenue DESC) AS row_num
      FROM movies
      ) RANKED WHERE row_num = 1;
      

# Avg. revenue / year certificate wise
SELECT 'Year', Certificate, AVG(Revenue) AS avg_revenue
FROM movies
GROUP BY Certificate;


# Release date of a particular movie
SELECT Title, 'Year'
FROM movies
WHERE Title = 'The Shawshank Redemption'; 


# Movies with similar genre
SELECT Title, Genre
FROM movies
WHERE Genre LIKE '% Action %' OR Genre LIKE '% Adventure %';


# To get the Director, Cast names 
SELECT Title, Director, Cast 
FROM movies
WHERE Director IS NOT NULL AND Cast IS NOT NULL
GROUP BY Title;


#  Top Genres by Avg. revenue
SELECT Genre, AVG(Revenue) AS avg_revenue
FROM movies
GROUP BY Genre
ORDER BY avg_revenue DESC 
LIMIT 3;


# Directors who directed multiple genres
SELECT Director, COUNT( DISTINCT Genre ) AS num_genre_directed
FROM movies
GROUP BY Director
HAVING num_genre_directed > 1;


# Movies with rating above Avg. rating
SELECT Title, Rating 
FROM movies
WHERE Rating > ( SELECT AVG(Rating) 
				 FROM movies );
                 
                 
# Directors with movies released in a specific year
SELECT DISTINCT Director
FROM movies
WHERE 'Year' = ( SELECT MIN('Year') 
                 FROM movies);
                 
                 
# Movies similar to Cast members
SELECT Title, Cast
FROM movies
WHERE Cast IN ( SELECT Cast 
                FROM movies );


# Avg. revenue per Director
SELECT Director, AVG(Revenue) AS avg_revenue
FROM movies 
GROUP BY Director;


# Combined runtime of movies genre wise
SELECT Genre, SUM(Runtime) AS combined_runtime
FROM movies
GROUP BY Genre;


# Difference between Avg. Rating of movies released before 2000 and after 2000
SELECT AVG(Before2000) - AVG(After2000)
FROM (
       SELECT AVG(Rating) AS 'avg'
	   FROM movies
	   WHERE 'Year' < '2000'
       GROUP BY Title
      ) AS Before2000,
      ( SELECT AVG(Rating) AS 'avg'
		FROM movies
        WHERE Year > '2000'
        GROUP BY Title
	  ) AS After2000;
      
      
# Directors who directed more than one movie 
SELECT Title, Director 
FROM movies
WHERE ( SELECT COUNT(*) FROM movies
        WHERE Director > 1
        ORDER BY Title, Director );
        

# Movies with highest average rating
SELECT Title, MAX(avg_rating) AS 'Rating'
FROM movies
WHERE ( SELECT AVG(Rating) AS avg_rating
        FROM movies
        GROUP BY Title );
        
        
# Movies with lowest average rating
SELECT Title, MIN(avg_rating) AS 'Rating'
FROM movies
WHERE ( SELECT AVG(Rating) AS avg_rating
        FROM movies
        GROUP BY Title );
        
        
# Director with movies which recieved highest rating
SELECT Director, Title, MAX(Rating) 
FROM movies
WHERE Director IS NOT NULL AND Rating IS NOT NULL
GROUP BY Director;


# Top 100 movies with a rating > 7.5
SELECT Title, 'Year', Rating
FROM movies
WHERE Rating > 7.5
ORDER BY Rating DESC
LIMIT 100;


# Top ten action movies with highest rating
SELECT Title, Genre, Rating
FROM movies 
WHERE Genre = 'Action'
ORDER BY Rating DESC
LIMIT 10;


# Movies with highest rating and less runtime
SELECT Title, Runtime, Rating
FROM movies
ORDER BY Rating DESC, Runtime ASC
LIMIT 100;


# Movies with highest rating starred by Leonardo di caprio
SELECT Title, Cast, Rating
FROM movies
WHERE Cast = 'Leonardo Di Caprio'
ORDER BY Rating DESC;


# Highest Grossing movie in a particular year
SELECT Title, Genre, 'Year', Revenue
FROM movies
WHERE 'Year' = '2020'
ORDER BY Revenue DESC;


# What are the top 10 highest rated movies
SELECT Title, Rating
FROM movies
ORDER BY Rating DESC
LIMIT 10;


# How many movies were released each year
SELECT Year, COUNT(*) AS Total_Movies
FROM movies
GROUP BY Year;


# What is the average runtime of movies by genre
SELECT Genre, AVG(Runtime) AS Avg_Runtime
FROM movies
GROUP BY Genre;


# Which director has directed the most number of movies
SELECT Director, COUNT(*) AS Movie_Count
FROM movies
GROUP BY Director
ORDER BY Movie_Count DESC
LIMIT 1;


# What is the total revenue generated by each certification rating
SELECT Certificate, SUM(Revenue) AS Total_Revenue
FROM movies
GROUP BY Certificate;


# How many movies were released in each decade
SELECT CONCAT(LEFT(Year, 3), '0s') AS Decade, COUNT(*) AS Movie_Count
FROM movies
GROUP BY LEFT(Year, 3);


# What is the revenue trend over the years
SELECT Year, SUM(Revenue) AS Total_Revenue
FROM movies
GROUP BY Year
ORDER BY Year;


# Which genre has the highest average rating
SELECT Genre, AVG(Rating) AS Avg_Rating
FROM movies
GROUP BY Genre
ORDER BY Avg_Rating DESC
LIMIT 1;


# What is the distribution of ratings for movies released in 2020
SELECT Rating, COUNT(*) AS Movie_Count
FROM movies
WHERE Year = '2020'
GROUP BY Rating;


# What is the average rating of movies directed by each director
SELECT Director, AVG(Rating) AS Avg_Rating
FROM movies
GROUP BY Director;


# Which actor/actress appears in the most number of movies
SELECT Cast, COUNT(*) AS Movie_Count
FROM movies
GROUP BY Cast
ORDER BY Movie_Count DESC
LIMIT 1;


# What is the revenue trend for each genre over the years
SELECT Genre, Year, SUM(Revenue) AS Total_Revenue
FROM movies
GROUP BY Genre, Year
ORDER BY Genre, Year;


# What is the cumulative revenue generated over the years for each genre
SELECT Genre, Year, Revenue, 
       SUM(Revenue) OVER (PARTITION BY Genre ORDER BY Year) AS Cumulative_Revenue
FROM movies;


# How many movies have a Metascore greater than 70
SELECT COUNT(*) AS High_Metascore_Movies
FROM movies
WHERE Metascore > 70;


# What percentage of movies are rated R
SELECT (COUNT(*) / (SELECT COUNT(*) FROM movies)) * 100 AS Percentage_Rated_R
FROM movies
WHERE Certificate = 'R';


# Which directors have directed movies in multiple genres
SELECT Director, COUNT(DISTINCT Genre) AS Genre_Count
FROM movies
GROUP BY Director
HAVING Genre_Count > 1;


# What is the average rating of movies longer than 2 hours
SELECT AVG(Rating) AS Avg_Rating
FROM movies
WHERE Runtime > 120;


# Which movies have revenue greater than the average revenue
SELECT Title, Revenue
FROM movies
WHERE Revenue > (SELECT AVG(Revenue) 
                 FROM movies);


# What is the most common certification rating for movies released in each year
SELECT Year, Certificate, COUNT(*) AS Rating_Count
FROM movies
GROUP BY Year, Certificate
ORDER BY Year, Rating_Count DESC
LIMIT 1;


# Which director has the highest average revenue per movie
SELECT Director, AVG(Revenue) AS Avg_Revenue_Per_Movie
FROM movies
GROUP BY Director
ORDER BY Avg_Revenue_Per_Movie DESC
LIMIT 1;


# Movies with a rating higher than their genre's average rating
SELECT m.Title, m.Rating, g.Genre_Avg_Rating
FROM movies m
JOIN (
	  SELECT Genre, AVG(Rating) AS Genre_Avg_Rating 
      FROM movies 
	  GROUP BY Genre
      ) g
ON m.Genre = g.Genre
WHERE m.Rating > g.Genre_Avg_Rating;


# Movies with the same director and cast
SELECT Title, Director, Cast
FROM movies
WHERE (Director, Cast) IN (
                           SELECT Director, Cast 
                           FROM movies 
                           GROUP BY Director, Cast 
                           HAVING COUNT(*) > 1 
                           );
                           
                           
# Percentage of revenue generated by each certificate type
SELECT Certificate, (SUM(Revenue) / (SELECT SUM(Revenue) FROM movies)) * 100 AS Revenue_Percentage
FROM movies
GROUP BY Certificate;


# Movies with the highest revenue in each genre
SELECT m.Title, m.Revenue, m.Genre
FROM movies m
JOIN (
    SELECT Genre, MAX(Revenue) AS Max_Revenue
    FROM movies
    GROUP BY Genre
) g ON m.Genre = g.Genre AND m.Revenue = g.Max_Revenue;


# Movies where the revenue exceeds the average revenue of movies released in the same year
SELECT m.Title, m.Revenue, AVG(m2.Revenue) AS Avg_Revenue
FROM movies m
JOIN movies m2 
ON m.Year = m2.Year
GROUP BY m.Title, m.Revenue
HAVING m.Revenue > AVG(m2.Revenue);
